/*
datatypes.c - Une
Modified 2023-02-10
*/

/* Header-specific includes. */
#include "datatypes.h"

/* Implementation-specific includes. */
#include "int.h"
#include "flt.h"
#include "str.h"
#include "list.h"
#include "void.h"
#include "function.h"
#include "builtin.h"

une_datatype une_datatypes[] = {
  {
    .type = UNE_RT_VOID,
    .as_int = NULL,
    .as_flt = NULL,
    .as_str = NULL,
    .represent = &une_datatype_void_represent,
    .is_true = &une_datatype_void_is_true,
    .is_equal = NULL,
    .is_greater = NULL,
    .is_greater_or_equal = NULL,
    .is_less = NULL,
    .is_less_or_equal = NULL,
    .add = NULL,
    .sub = NULL,
    .mul = NULL,
    .div = NULL,
    .fdiv = NULL,
    .mod = NULL,
    .pow = NULL,
    .negate = NULL,
    .get_len = NULL,
    .is_valid_index_type = NULL,
    .is_valid_index = NULL,
    .is_valid_element = NULL,
    .get_index = NULL,
    .seek_index = NULL,
    .copy = NULL,
    .free_members = NULL,
    .call = NULL,
  },
  {
    .type = UNE_RT_INT,
    .as_int = &une_datatype_int_as_int,
    .as_flt = &une_datatype_int_as_flt,
    .as_str = &une_datatype_int_as_str,
    .represent = &une_datatype_int_represent,
    .is_true = &une_datatype_int_is_true,
    .is_equal = &une_datatype_int_is_equal,
    .is_greater = &une_datatype_int_is_greater,
    .is_greater_or_equal = &une_datatype_int_is_greater_or_equal,
    .is_less = &une_datatype_int_is_less,
    .is_less_or_equal = &une_datatype_int_is_less_or_equal,
    .add = &une_datatype_int_add,
    .sub = &une_datatype_int_sub,
    .mul = &une_datatype_int_mul,
    .div = &une_datatype_int_div,
    .fdiv = &une_datatype_int_fdiv,
    .mod = &une_datatype_int_mod,
    .pow = &une_datatype_int_pow,
    .negate = &une_datatype_int_negate,
    .get_len = NULL,
    .is_valid_index_type = NULL,
    .is_valid_index = NULL,
    .is_valid_element = NULL,
    .get_index = NULL,
    .seek_index = NULL,
    .copy = NULL,
    .free_members = NULL,
    .call = NULL,
  },
  {
    .type = UNE_RT_FLT,
    .as_int = &une_datatype_flt_as_int,
    .as_flt = &une_datatype_flt_as_flt,
    .as_str = &une_datatype_flt_as_str,
    .represent = &une_datatype_flt_represent,
    .is_true = &une_datatype_flt_is_true,
    .is_equal = &une_datatype_flt_is_equal,
    .is_greater = &une_datatype_flt_is_greater,
    .is_greater_or_equal = &une_datatype_flt_is_greater_or_equal,
    .is_less = &une_datatype_flt_is_less,
    .is_less_or_equal = &une_datatype_flt_is_less_or_equal,
    .add = &une_datatype_flt_add,
    .sub = &une_datatype_flt_sub,
    .mul = &une_datatype_flt_mul,
    .div = &une_datatype_flt_div,
    .fdiv = &une_datatype_flt_fdiv,
    .mod = &une_datatype_flt_mod,
    .pow = &une_datatype_flt_pow,
    .negate = &une_datatype_flt_negate,
    .get_len = NULL,
    .is_valid_index_type = NULL,
    .is_valid_index = NULL,
    .is_valid_element = NULL,
    .get_index = NULL,
    .seek_index = NULL,
    .copy = NULL,
    .free_members = NULL,
    .call = NULL,
  },
  {
    .type = UNE_RT_STR,
    .as_int = &une_datatype_str_as_int,
    .as_flt = &une_datatype_str_as_flt,
    .as_str = &une_datatype_str_as_str,
    .represent = &une_datatype_str_represent,
    .is_true = &une_datatype_str_is_true,
    .is_equal = &une_datatype_str_is_equal,
    .is_greater = &une_datatype_str_is_greater,
    .is_greater_or_equal = &une_datatype_str_is_greater_or_equal,
    .is_less = &une_datatype_str_is_less,
    .is_less_or_equal = &une_datatype_str_is_less_or_equal,
    .add = &une_datatype_str_add,
    .sub = NULL,
    .mul = &une_datatype_str_mul,
    .div = NULL,
    .fdiv = NULL,
    .mod = NULL,
    .pow = NULL,
    .negate = NULL,
    .get_len = &une_datatype_str_get_len,
    .is_valid_index_type = &une_datatype_str_is_valid_index_type,
    .is_valid_index = &une_datatype_str_is_valid_index,
    .is_valid_element = &une_datatype_str_is_valid_element,
    .get_index = &une_datatype_str_get_index,
    .seek_index = &une_datatype_str_seek_index,
    .copy = &une_datatype_str_copy,
    .free_members = &une_datatype_str_free_members,
    .call = NULL,
  },
  {
    .type = UNE_RT_LIST,
    .as_int = NULL,
    .as_flt = NULL,
    .as_str = NULL,
    .represent = &une_datatype_list_represent,
    .is_true = &une_datatype_list_is_true,
    .is_equal = &une_datatype_list_is_equal,
    .is_greater = &une_datatype_list_is_greater,
    .is_greater_or_equal = &une_datatype_list_is_greater_or_equal,
    .is_less = &une_datatype_list_is_less,
    .is_less_or_equal = &une_datatype_list_is_less_or_equal,
    .add = &une_datatype_list_add,
    .sub = NULL,
    .mul = &une_datatype_list_mul,
    .div = NULL,
    .fdiv = NULL,
    .mod = NULL,
    .pow = NULL,
    .negate = NULL,
    .get_len = &une_datatype_list_get_len,
    .is_valid_index_type = &une_datatype_list_is_valid_index_type,
    .is_valid_index = &une_datatype_list_is_valid_index,
    .is_valid_element = &une_datatype_list_is_valid_element,
    .get_index = &une_datatype_list_get_index,
    .seek_index = &une_datatype_list_seek_index,
    .copy = &une_datatype_list_copy,
    .free_members = &une_datatype_list_free_members,
    .call = NULL,
  },
  {
    .type = UNE_RT_FUNCTION,
    .as_int = NULL,
    .as_flt = NULL,
    .as_str = NULL,
    .represent = &une_datatype_function_represent,
    .is_true = &une_datatype_function_is_true,
    .is_equal = NULL,
    .is_greater = NULL,
    .is_greater_or_equal = NULL,
    .is_less = NULL,
    .is_less_or_equal = NULL,
    .add = NULL,
    .sub = NULL,
    .mul = NULL,
    .div = NULL,
    .fdiv = NULL,
    .mod = NULL,
    .pow = NULL,
    .negate = NULL,
    .get_len = NULL,
    .is_valid_index_type = NULL,
    .is_valid_index = NULL,
    .is_valid_element = NULL,
    .get_index = NULL,
    .seek_index = NULL,
    .copy = NULL,
    .free_members = NULL,
    .call = &une_datatype_function_call,
  },
  {
    .type = UNE_RT_BUILTIN,
    .as_int = NULL,
    .as_flt = NULL,
    .as_str = NULL,
    .represent = &une_datatype_builtin_represent,
    .is_true = &une_datatype_builtin_is_true,
    .is_equal = NULL,
    .is_greater = NULL,
    .is_greater_or_equal = NULL,
    .is_less = NULL,
    .is_less_or_equal = NULL,
    .add = NULL,
    .sub = NULL,
    .mul = NULL,
    .div = NULL,
    .fdiv = NULL,
    .mod = NULL,
    .pow = NULL,
    .negate = NULL,
    .get_len = NULL,
    .is_valid_index_type = NULL,
    .is_valid_index = NULL,
    .is_valid_element = NULL,
    .get_index = NULL,
    .seek_index = NULL,
    .copy = NULL,
    .free_members = NULL,
    .call = &une_datatype_builtin_call,
  },
};
